### ISSUE TITLE
Wrong parent project references in `smp-docker` and `smp-wls-deploy`

### ISSUE THREAD

**Issue by sschuberth** [nordic-institute/harmony-smp#20]
The artifact coordinates in

https://github.com/nordic-institute/harmony-smp/blob/0eb2e4598d3ab2e2d68af1aee8263f854df0843c/smp-docker/pom.xml#L8-L13

and

https://github.com/nordic-institute/harmony-smp/blob/0eb2e4598d3ab2e2d68af1aee8263f854df0843c/smp-wls-deploy/pom.xml#L4-L9

do not match the ones in the referred `pom.xml` in the root directory, which has

https://github.com/nordic-institute/harmony-smp/blob/0eb2e4598d3ab2e2d68af1aee8263f854df0843c/pom.xml#L18-L22

So I believe either the `relativePath` needs to go away, or the artifact coordinates need to be changed to match the ones from the root `pom.xml`.

**Comment by petkivim** [comment]
@sschuberth Those subdirectories are not included in the distributed artifacts and therefore, they can be excluded. I've updated the ORT configuration and excluded them (0f69fafc497f3e9be5f0719dcda545b4fee003e0). Is that sufficient?

**Comment by sschuberth** [comment]
> Is that sufficient?

While that indeed hides the problem from the ORT analysis, I believe it's a real problem that should be fixed anyway.

**Comment by petkivim** [comment]
Those modules are not used by Harmony SMP and the current configuration doesn't affect the Harmony build. Therefore, I'd leave the configuration as-is if the problem on the ORT side has been resolved.

**Comment by sschuberth** [comment]
The problem on the ORT side has been resolved by the configuration change, so feel free to close this.

However, please be advised that you can reproduce the issue also with plain Maven by running e.g. `./mvnw -f smp-docker/pom.xml help:effective-pom` which gives

```
[ERROR]   The project eu.europa.ec.edelivery:smp-docker:5.0-RC2-SNAPSHOT (harmony-smp/smp-docker/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for eu.europa.ec.edelivery:smp-docker:5.0-RC2-SNAPSHOT: Could not find artifact eu.europa.ec.edelivery:smp-modules:pom:5.0-RC2-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 13 -> [Help 2]
```
